In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
data = pd.read_csv('toy_dataset.csv')

In [3]:
data.head()

Number    City Gender  Age   Income Illness
0       1  Dallas   Male   41  40367.0      No
1       2  Dallas   Male   54  45084.0      No
2       3  Dallas   Male   42  52483.0      No
3       4  Dallas   Male   40  40941.0      No
4       5  Dallas   Male   46  50289.0      No

In [4]:
len(data)

150000

In [5]:
data.describe()

Number            Age         Income
count  150000.000000  150000.000000  150000.000000
mean    75000.500000      44.950200   91252.798273
std     43301.414527      11.572486   24989.500948
min         1.000000      25.000000    -654.000000
25%     37500.750000      35.000000   80867.750000
50%     75000.500000      45.000000   93655.000000
75%    112500.250000      55.000000  104519.000000
max    150000.000000      65.000000  177157.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   Number   150000 non-null  int64  
 1   City     150000 non-null  object 
 2   Gender   150000 non-null  object 
 3   Age      150000 non-null  int64  
 4   Income   150000 non-null  float64
 5   Illness  150000 non-null  object 
dtypes: float64(1), int64(2), object(3)
memory usage: 6.9+ MB


In [7]:
data.tail()

Number    City  Gender  Age    Income Illness
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

In [8]:
data1=data.drop('Number',axis=1)

In [9]:
data1.head()

City Gender  Age   Income Illness
0  Dallas   Male   41  40367.0      No
1  Dallas   Male   54  45084.0      No
2  Dallas   Male   42  52483.0      No
3  Dallas   Male   40  40941.0      No
4  Dallas   Male   46  50289.0      No

In [10]:
data1["Age"].describe()

count    150000.000000
mean         44.950200
std          11.572486
min          25.000000
25%          35.000000
50%          45.000000
75%          55.000000
max          65.000000
Name: Age, dtype: float64

In [11]:
# data1["Age"]=((data1["Age"]-data1["Age"].min())/(data1["Age"].max()-data1["Age"].min()))

In [12]:
# data1.loc[0, 'Age'] = np.nan 

In [13]:
np.array(sorted(data1.Age.unique()))

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65], dtype=int64)

In [14]:
pd.qcut(data1.Age, q=8).head(7)

0    (40.0, 45.0]
1    (50.0, 55.0]
2    (40.0, 45.0]
3    (35.0, 40.0]
4    (45.0, 50.0]
5    (35.0, 40.0]
6    (30.0, 35.0]
Name: Age, dtype: category
Categories (8, interval[float64]): [(24.999, 30.0] < (30.0, 35.0] < (35.0, 40.0] < (40.0, 45.0] < (45.0, 50.0] < (50.0, 55.0] < (55.0, 60.0] < (60.0, 65.0]]

In [15]:
data1["Age"]=pd.qcut(data1.Age, q=8)

In [16]:
data1.head(7)

City  Gender           Age   Income Illness
0  Dallas    Male  (40.0, 45.0]  40367.0      No
1  Dallas    Male  (50.0, 55.0]  45084.0      No
2  Dallas    Male  (40.0, 45.0]  52483.0      No
3  Dallas    Male  (35.0, 40.0]  40941.0      No
4  Dallas    Male  (45.0, 50.0]  50289.0      No
5  Dallas  Female  (35.0, 40.0]  50786.0      No
6  Dallas  Female  (30.0, 35.0]  33155.0      No

In [17]:
data1.tail()

City  Gender             Age    Income Illness
149995  Austin    Male    (45.0, 50.0]   93669.0      No
149996  Austin    Male  (24.999, 30.0]   96748.0      No
149997  Austin    Male  (24.999, 30.0]  111885.0      No
149998  Austin    Male  (24.999, 30.0]  111878.0      No
149999  Austin  Female    (35.0, 40.0]   87251.0      No

In [18]:
# data1['Age'] = pd.cut(data1['Age'], range(data1['Age'].min(), data1['Age'].max(), 5))

In [19]:
data1.shape

(150000, 5)

In [20]:
data1["Age"].value_counts()

(24.999, 30.0]    20910
(40.0, 45.0]      18936
(50.0, 55.0]      18731
(35.0, 40.0]      18700
(45.0, 50.0]      18677
(30.0, 35.0]      18645
(55.0, 60.0]      18453
(60.0, 65.0]      16948
Name: Age, dtype: int64

In [21]:
np.array(sorted(data1.Income.unique()))

array([  -654.,    584.,   2474., ..., 173991., 176746., 177157.])

In [22]:
data1[data1["Income"]<0]

City  Gender           Age  Income Illness
245  Dallas  Female  (35.0, 40.0]  -654.0     Yes

In [23]:
data1.drop(data1[data1['Income'] < 0].index, inplace = True) 

In [24]:
np.array(sorted(data1.Income.unique()))

array([   584.,   2474.,   2667., ..., 173991., 176746., 177157.])

In [25]:
pd.qcut(data1.Income, q=36).head(7)

0      (36184.833, 43068.0]
1      (43068.0, 48930.833]
2    (48930.833, 55223.444]
3      (36184.833, 43068.0]
4    (48930.833, 55223.444]
5    (48930.833, 55223.444]
6      (583.999, 36184.833]
Name: Income, dtype: category
Categories (36, interval[float64]): [(583.999, 36184.833] < (36184.833, 43068.0] < (43068.0, 48930.833] < (48930.833, 55223.444] ... (116787.556, 123890.333] < (123890.333, 132768.778] < (132768.778, 141375.778] < (141375.778, 177157.0]]

In [26]:
pd.qcut(data1.Income, q=36).value_counts()

(86119.333, 87540.0]        4171
(92508.0, 93655.0]          4169
(55223.444, 63214.0]        4169
(78433.889, 80868.0]        4169
(88854.556, 90101.0]        4169
(36184.833, 43068.0]        4168
(103067.0, 104519.0]        4168
(99338.0, 100525.0]         4168
(98162.444, 99338.0]        4168
(93655.0, 94757.0]          4167
(48930.833, 55223.444]      4167
(70570.333, 75277.278]      4167
(80868.0, 82905.0]          4167
(132768.778, 141375.778]    4167
(141375.778, 177157.0]      4167
(583.999, 36184.833]        4167
(100525.0, 101749.0]        4167
(116787.556, 123890.333]    4167
(112741.833, 116787.556]    4167
(107961.0, 110076.0]        4167
(106096.111, 107961.0]      4167
(84608.0, 86119.333]        4166
(123890.333, 132768.778]    4166
(75277.278, 78433.889]      4166
(95876.0, 97039.0]          4166
(90101.0, 91346.0]          4166
(91346.0, 92508.0]          4166
(97039.0, 98162.444]        4166
(101749.0, 103067.0]        4165
(110076.0, 112741.833]      4165
(43068.0, 

In [27]:
data1["Income"]=pd.qcut(data1.Income, q=36)

In [28]:
data1.head()

City Gender           Age                  Income Illness
0  Dallas   Male  (40.0, 45.0]    (36184.833, 43068.0]      No
1  Dallas   Male  (50.0, 55.0]    (43068.0, 48930.833]      No
2  Dallas   Male  (40.0, 45.0]  (48930.833, 55223.444]      No
3  Dallas   Male  (35.0, 40.0]    (36184.833, 43068.0]      No
4  Dallas   Male  (45.0, 50.0]  (48930.833, 55223.444]      No

In [29]:
data1.shape

(149999, 5)

In [30]:
le = preprocessing.LabelEncoder()

In [31]:
data1['City'] = le.fit_transform(data1['City'])
data1['Gender'] = le.fit_transform(data1['Gender'])
data1['Age'] = le.fit_transform(data1['Age'])
data1['Income'] = le.fit_transform(data1['Income'])
data1['Illness'] = le.fit_transform(data1['Illness'])

In [32]:
data1.head()

City  Gender  Age  Income  Illness
0     2       1    3       1        0
1     2       1    5       2        0
2     2       1    3       3        0
3     2       1    2       1        0
4     2       1    4       3        0

In [33]:
data1[data1["Illness"]==1]

City  Gender  Age  Income  Illness
10         2       0    4       1        1
17         2       1    2       2        1
23         2       0    0       0        1
29         2       1    3       2        1
38         2       0    7       1        1
...      ...     ...  ...     ...      ...
149847     0       0    5       5        1
149886     0       1    7      31        1
149936     0       1    1      25        1
149949     0       1    0      18        1
149980     0       0    5      14        1

[12138 rows x 5 columns]

In [34]:
from sklearn.naive_bayes import CategoricalNB

In [35]:
model = CategoricalNB()

In [36]:
features = data1[['City','Gender','Age','Income']]
label = data1['Illness']

In [37]:
features

City  Gender  Age  Income
0          2       1    3       1
1          2       1    5       2
2          2       1    3       3
3          2       1    2       1
4          2       1    4       3
...      ...     ...  ...     ...
149995     0       1    4      18
149996     0       1    0      20
149997     0       1    0      30
149998     0       1    0      30
149999     0       0    2      12

[149999 rows x 4 columns]

In [45]:
features.head(30)

City  Gender  Age  Income
0      2       1    3       1
1      2       1    5       2
2      2       1    3       3
3      2       1    2       1
4      2       1    4       3
5      2       0    2       3
6      2       0    1       0
7      2       1    2       0
8      2       1    5       5
9      2       0    0       3
10     2       0    4       1
11     2       1    4       3
12     2       1    4       4
13     2       0    3       3
14     2       0    7       1
15     2       1    3       0
16     2       1    0       3
17     2       1    2       2
18     2       1    4       3
19     2       0    1       0
20     2       1    6       0
21     2       1    1       2
22     2       0    1       0
23     2       0    0       0
24     2       1    6       3
25     2       1    7       0
26     2       1    6       4
27     2       1    3       4
28     2       1    1       3
29     2       1    3       2

In [38]:
res = model.fit(features, label)

In [39]:
res

CategoricalNB()

In [40]:
y_predict = model.predict(features)

In [41]:
from sklearn import metrics

In [42]:
print('accuracy = ', metrics.accuracy_score(label,y_predict ))

accuracy =  0.9190794605297369


In [52]:
x = [[2 ,1 ,3 ,2]]

In [53]:
y = model.predict(x)

In [54]:
y

array([0])

In [216]:
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [55]:
label

0         0
1         0
2         0
3         0
4         0
         ..
149995    0
149996    0
149997    0
149998    0
149999    0
Name: Illness, Length: 149999, dtype: int32